### ISSUE TITLE
Fluffy state network implementation roadmap

### ISSUE THREAD

**Issue by mynameisdaniil** [status-im/nimbus-eth1#1900]
This issue intended to track general overview of State network implementation progress. This issue will be modified to reflect progress and new developments in this area.

- [ ] Implement fake bridge sending blobs of random data
- [ ] Make initial implementation of State network to collect and store this data
- [ ] Modify fake bridge to send real data either from files.
- [ ] Modify fake bridge into real one i.e. make it send state data from mainnet.
- [ ] ???
- [ ] PROFIT!

---

At the moment I'm unable to see it though and formulate a real plan. So all suggestion are welcome. Maybe just throw in some ideas in the comments and I will modify this post accordingly. @zah @kdeme

**Comment by kdeme** [comment]
Could you explain me the goal of the first two points?
As I see it, pumping random data into the State network would only test the portal wire protocol, lookup, database, etc.. These parts are already tested as we have a working History network.

**Comment by mynameisdaniil** [comment]
Point is to make it manageable. I've never implemented any of those parts before, so I want to see a progress and get the feel of how things work.

**Comment by kdeme** [comment]
> This issue intended to track general overview of State network implementation progress

You basically already define it with this sentence,  but the goal of this issue should be to get a good overview of what is already implemented, what we clearly need to implement still and what needs further investigation and/or research.
I have some steps in mind here (which I have also communicated already), but as you have been investigating this, you may be able to fine grain it more. Obviously, some of that fine gaining will come in time as we figure things out and some tasks might get scrapped/adjusted, and all that is fine.

Now, an issue like this should not just be there for you to track your own progress. It is also for anyone else to see what the current state is. And more importantly, if somebody joins in or continues the work, to be able to easily do so without redoing a lot of the initial investigation.

The first few points do not really contribute anything to that, so I don't think they belong here as part of a State network roadmap.

> I guess the point of all this is to make myself comfortable and catch up on things

Okay, I understand. However, this is an issue that is separate from the task list here. 
One possible way to achieve that would be to create an example of a custom blob network with documentation, as a sort of demonstration/tutorial. That way it would be useful for future devs too. I do wish this had been communicated much earlier.

**Comment by kdeme** [comment]
Closing this in favour of https://github.com/status-im/nimbus-eth1/issues/1923
