### ISSUE TITLE
TODO list related to Berlin HF

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#540]
[EIP 2070](https://eips.ethereum.org/EIPS/eip-2070) (Berlin HF):

* [x] [EIP 2315](https://eips.ethereum.org/EIPS/eip-2315) : Simple Subroutines for the EVM
* [x] [EIP 2537](https://eips.ethereum.org/EIPS/eip-2537) : BLS12-381 curve operations
  * [x] BLS12_G1ADD - to perform point addition on a curve defined over prime field
  * [x] BLS12_G1MUL - to perform point multiplication on a curve defined over prime field
  * [x] BLS12_G1MULTIEXP - to perform multiexponentiation on a curve defined over prime field
  * [x] BLS12_G2ADD - to perform point addition on a curve twist defined over quadratic extension of the base field
  * [x] BLS12_G2MUL - to perform point multiplication on a curve twist defined over quadratic extension of the base field
  * [x] BLS12_G2MULTIEXP - to perform multiexponentiation on a curve twist defined over quadratic extension of the base field
  * [x] BLS12_PAIRING - to perform a pairing operations between a set of pairs of (G1, G2) points
  * [x] BLS12_MAP_FP_TO_G1 - maps base field element into the G1 point
  * [x] BLS12_MAP_FP2_TO_G2 - maps extension field element into the G2 point
* [x] [EIP 2046](https://eips.ethereum.org/EIPS/eip-2046) : Reduced gas cost for static calls made to precompiles
* [x] [EIP 2565](https://eips.ethereum.org/EIPS/eip-2565) : Repricing of the EIP-198 ModExp precompile
* [x] [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) : Gas cost increases for state access
* [x] add new test fixtures for GST and BC test suite
* [x] [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718): Typed transaction envelope
* [x] [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930): Optional access list
* [ ] [EIP 2364](https://eips.ethereum.org/EIPS/eip-2364) : ETH Wire Protocol 64
* [ ] [EIP 2464](https://eips.ethereum.org/EIPS/eip-2464) : ETH Wire Protocol 65
* [ ] [EIP 2481](https://eips.ethereum.org/EIPS/eip-2481) : ETH Wire Protocol 66
* [ ] fixes fast sync algorithm to accommodate peers with either eth/63 - eth/66 wire protocol

**Comment by jangko** [comment]
closing, fixed by #661
