### ISSUE TITLE
Implement simple async worker for PoA sealing engine 

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#801]
This issue will function as a reminder for me to consolidate various elements and form a working sealer. The goal is to pass clique smoke test of hive, and later will be used in rpc tests of hive after the txpool completed.

Requirements:
- [x] legacy gasLimit, EIP-1559 gasLimit, EIP-1559 baseFee, from #741
- [x] async tick event will use simple async timer combined with `cliquePeriod` from #777
- [x] the sole signer, taken from #787
- [x] PoA validator from #748 and #745
- [ ] Tx Pool will come later if it's ready, fow now we can omit Tx Pool, but should contains a working tx execution  accompanied by a test.
- [ ] uncles can be omitted to simplify the initial implementation and can be added later.
- [ ] async lock/guard can be omitted for simplicity, and can be added later if it interfere with block sync
